### ISSUE TITLE
Link zu Datenschutz und Terms of Use in App integrieren.

### ISSUE THREAD

**Issue by ThingsOfficer** [reinehr/BoatOfficerMobile#101]
<img width="690" alt="Bildschirmfoto 2021-01-06 um 19 01 28" src="https://user-images.githubusercontent.com/61187940/103804021-b853ba00-5051-11eb-9b37-cb324004bf5d.png">

Links: 
https://boatofficer.com/privacy
https://boatofficer.com/app/eula

**Comment by reinehr** [comment]
Beide Links im Impressum eingebaut.
