### ISSUE TITLE
Beschriftung X Achse in Diagrammen bei negativen Werten ist defekt

### ISSUE THREAD

**Issue by ThingsOfficer** [reinehr/BoatOfficerMobile#103]
Siehe Bild: 

<img width="343" alt="Bildschirmfoto 2021-01-28 um 19 56 00" src="https://user-images.githubusercontent.com/61187940/106199019-17ba6b00-61b5-11eb-9698-67cac52a091e.png">

**Comment by reinehr** [comment]
Nur in iOS. In Android sieht es gut aus.
