### ISSUE TITLE
Unter GoogleMap: Geschwindigkeit, Kurs und Accuracy anzeigen

### ISSUE THREAD

**Issue by reinehr** [reinehr/BoatOfficerMobile#23]

**Comment by ThingsOfficer** [comment]
Zukünftig ggf. auch den Kurs als Richtungspfeil direkt an das Positions-Icon. (sofern Geschwindigkeit > 10 km/h)

**Comment by ThingsOfficer** [comment]
Außerdem den genauen Zeitpunkt (Datum, Zeit) der Position angeben. Denn "1 day ago" wäre sehr ungenau... ggf. ein paar Textzeilen unter der Karte für alles genannte vorsehen.

**Comment by reinehr** [comment]
Das Wichtigste tut. Was noch fehlt: 
Richtungspfeil in der Karte. Das würde ich jetzt mal in den Backlog schieben.
