### ISSUE TITLE
"Battery 2" konfigurierbar mach (ob es überhaupt eine gibt)

### ISSUE THREAD

**Issue by reinehr** [reinehr/BoatOfficerMobile#25]
Vorerst Battery 2 ausblenden. Sobald es ein Kabel für zwei Batterien gibt, per Settings einstellbare Anzeige.

**Comment by ThingsOfficer** [comment]
Zusätzlich sollten die Alarmgrenzwerte für die Batterie 2, wenn es gar keine zweite gibt auf 0 bzw. 60V gelegt werden, damit keine versehentlichen Alarme kommen.

**Comment by reinehr** [comment]
**UPDATE:** Vorerst beide wieder an machen, denn sonst kann man die Spannung des USB-Kabels nicht sehen. 
Das kann zu Verwirrungen führen, denn wenn das Kabel für eine externe Batterie angeschlossen ist, wird der Wert zweimal angezeigt. ->FAQ

**Comment by reinehr** [comment]
**UPDATE:** Battery 2 wird jetzt angezeigt. Um die Konfigurierbarkeit müssen wir uns noch Gedanken machen.
