### ISSUE TITLE
User Registration: Willkommens-Mail mit kleiner Anleitung und eventuell einen "Aktivierungslink"

### ISSUE THREAD

**Issue by reinehr** [reinehr/BoatOfficerMobile#30]
Außerdem: Anmeldung für  z.B. Produktinformation

**Comment by ThingsOfficer** [comment]
Funktioniert das eigentlich auch bei Anmeldung über Apple, Google oder facebook? Haben wir dann überhaupt Kenntniss der Mail-Adressen?
