### ISSUE TITLE
Impressum in den allgemeinen Einstellungen

### ISSUE THREAD

**Issue by reinehr** [reinehr/BoatOfficerMobile#33]

**Comment by reinehr** [comment]
@ThingsOfficer schreibst du mir hier ein Impressum, das in der App erscheinen soll? Am besten englisch und deutsch.

**Comment by ThingsOfficer** [comment]
ThingsOfficer GmbH
Atelierstr. 29, c/o Werk1, 
81671 München, 
Germany
info@boatofficer.com
