### ISSUE TITLE
In Boat Settings die Seriennummer, Firmwareversion anzeigen

### ISSUE THREAD

**Issue by reinehr** [reinehr/BoatOfficerMobile#34]

**Comment by ThingsOfficer** [comment]
Zur Entschlüsselung der Rohdaten: 

<img width="784" alt="Bildschirmfoto 2020-09-16 um 09 27 29" src="https://user-images.githubusercontent.com/61187940/93305506-e3926f00-f7fe-11ea-9ce6-c88ecb6853cd.png">

**Comment by ThingsOfficer** [comment]
Firmwareversion passt noch nicht ganz - müssen wir uns noch mal anschauen. Da scheint was verdreht.

**Comment by ThingsOfficer** [comment]
obwohl... ne, passt... die Firmwareversionen sind eben nicht aktuell in der Datenbank. Müssen mal wieder abgefragt werden per LoRaWAN.
