### ISSUE TITLE
Hinweis in Alarm History, wenn keine Alarme vorhanden sind

### ISSUE THREAD

**Issue by ThingsOfficer** [reinehr/BoatOfficerMobile#36]
Damit der Nutzer sich nicht wundert eine Text-Anzeige in der History: "No alarms to view" o.ä.

**Comment by reinehr** [comment]
Das ist doch komplexer, als gedacht. Deshalb (und weil es keine essentielle Funktion ist) setze ich Priorität von 1 auf 2
