### ISSUE TITLE
Anzeige von Modi "Theft"

### ISSUE THREAD

**Issue by ThingsOfficer** [reinehr/BoatOfficerMobile#38]
Der BoatOfficer kann je nach Alarm ja in den "Theft" Modus schalten. 
In diesem sendet er alle 30 s die Position, also belastet extrem die verfügbare Airtime und die interne Batterie. 
Der Nutzer sollte wissen, wenn sich sein Boot in diesem Zustand befindet und es ggf. abstellen können - nein sogar dazu animiert werden es abzustellen. Er soll es nicht als Komfort verstehen alle 30 s die Position zu bekommen. 

Über das Naming müsste man ggf. noch mal reden.

**Comment by reinehr** [comment]
Die große Datenmenge macht auch die App langsam

**Comment by reinehr** [comment]
Theft-Mode wird erkannt an GPS über Port 11.
=> Push-Nachricht, wenn nicht unmittelbar davor schon eine versendet wurde (innerhalb 5 Minuten durch Alarm-Message)

Selbes Prinzip für SOS-Mode über Port 13. 

GPS auf Port 10 kommt einem Clear gleich für Theft und SOS

**Comment by ThingsOfficer** [comment]
Anmerkung: Push Nachricht dann senden, wenn nicht bereits eine "Boot in Bewegung" Nachricht beim Beginn  des Zustandes gesendet wurde, oder zwischendurch wieder eine GPS Position auf Port 10 kam. (Über 10 kommt die GPS Position nur, wenn es im Interval Modus ist.)

Am besten bekommt das Device in der Datenbank / App einen Zustandsautomaten... :
Zustände:
* Interval (Normal), Port: 10
* Theft Tracking, Port: 11
* SOS, Port: 12
* Racing, Port: 13
* Tracking, (Boot in Bewegung, aber kein Theft-Mode, weil entweder acknowledge oder Alarm "Position Jump" ist unterdrückt) Port: 14
* Mapping, Port: 15  (Entwickler Feature, sendet alle 20 s mit verschiedenen Datenraten die Position).
