### ISSUE TITLE
Handling von aktualisierten Download Werten (Config, ...)

### ISSUE THREAD

**Issue by ThingsOfficer** [reinehr/BoatOfficerMobile#43]
Wir haben ja das Problem besprochen, dass du, wenn du einen Alarmschwelle änderst eine Download Nachricht pushst. 
Wenn du kurz darauf einen zweiten Wert änderst, eine zweite Nachricht erstellt werden muss und dann die aktuellste Konfiguration erst beim übernächsten Download wirklich heruntergeladen wird. 

Dann haben wir überlegt immer "replace" zu wählen bei der Download-Option. Was aber andere Downloads löschen würde, die auch noch zu tun sind (bspw. Commands). 

Ich habe nachgedacht und nachgefragt. Siehe [TTN Forum](https://www.thethingsnetwork.org/forum/t/downlink-queue-clarification-wanted-first-last-replace-regarding-ports/38097)

Nun ist die Idee folgende:
* Die gesamte Download Queue wird immer wieder neu gepusht. 
* Die Mobile App (oder Backend?) prüfen, welche Kommandos zu senden sind und laden immer die aktuellste Downloadversion herunter bei bestimmten Events:
  * Alarm Setting geändert
  * Blocking Time für einen Alarm gesetzt
    * Blocking Time für ein Alarm wird um 1 Minute reduziert (anderes Thema)
* Die Rangordnung der Download Messages ist wichtig:
 0. Switch Mode (Port 40)
 1. User_Cfg (Port 31)
 2. Admin_Cfg (Port 32)
 3. Commands (Port 30)
 4. Request Device Info (Port 50)
 5. Blocking Times für message triggers (Ports 101 bis 131)

**Comment by reinehr** [comment]
Ist umgesetzt. Erst wird auf Port 31 gesendet mit "replace". Dann auf Port 32 und anschließend bei Bedarf auf den Ports 101 bis 131.
