### ISSUE TITLE
Möglichkeit über "General Settings" auch zu Boot Settings zu kommen 

### ISSUE THREAD

**Issue by ThingsOfficer** [reinehr/BoatOfficerMobile#54]
User erwartet dort auch Boot Settings, gerade wenn er nur ein Boot hat.

**Comment by reinehr** [comment]
Weil es inzwischen keine Boat Settings für alle Boote mehr gibt, sondern nur noch für je ein Boot, kann man auch nicht mehr mit nur einem Button aus den allgemeinen Einstellungen zu den Bootseinstellugnen gelangen.
