### ISSUE TITLE
Nutzer Führung Login/Logout/SignUp verbessern

### ISSUE THREAD

**Issue by ThingsOfficer** [reinehr/BoatOfficerMobile#56]
* Wenn der Nutzer gar nicht eingeloggt ist, sollte er auch nicht "Register new device" und "Logout" sehen. 

* Wenn man "Not registered yet?.." klickt, sollte die Überschrift der Page auch "Sign Up" und nicht "Login" heißen. 

* Wenn Nutzer eingeloggt ist, sollte er seinen Namen "Logged in as: pirat@boatofficer.com" bspw. auf der Seite sehen. 

* Ein iPhone Nutzer hat angegeben, dass die Schrift für E-Mail Adresse und Passwort beim Tippen schlecht zu lesen ist (blass?)

**Comment by reinehr** [comment]
Alle oben genannten Punkte sind umgesetzt. Was noch fehlt: Passwort zurücksetzen per E-Mail
