### ISSUE TITLE
Homescreen

### ISSUE THREAD

**Issue by reinehr** [reinehr/BoatOfficerMobile#69]
Wetter auf dem Home-Screen. Mit Wind und Wasserpegel. 

Bild + Name

Position

Alarm-Zusammenfassung

Modus (Theft, SOS, Connection lost)

**Comment by reinehr** [comment]
Es fehlt nur noch der Modus. Ich setze deshalb die Prio runter auf 2

**Comment by ThingsOfficer** [comment]
Modi Kennzeichnung in Map: 
Port 10 / 210, 16 /216: keine besondere Markierung
Port 11 / 211: "Unacknowledged Movement" - "Unbestätigte Bewegung"
Port 12 / 212: "SOS" - "SOS"
Port 13 / 213: Race Mode: nur Icon "runner"
Port 14 / 214: hmmm.... vllt. geschwindigkeit und richtung?
Port 15 / 215: Nur Icon "map-marked-alt"
