### ISSUE TITLE
Verwalten der eigenen Benachrichtigungen und Sichtbarkeiten der Boote

### ISSUE THREAD

**Issue by reinehr** [reinehr/BoatOfficerMobile#79]
Einstellungen -> "Meine Boote"

Man sieht eine Liste der Boote mit Hinweis, ob man Sailor, Officer oder Guard ist und welche Elemente sichtbar sind (weil der Officer es mir erlaubt hat und weil ich nicht auf "verbergen" geklickt habe)

Bei jedem Boot kann ich festlegen, ob ich es: 
1. generell sehen kann
2. Push-Nachrichten bekommen will

**Comment by reinehr** [comment]
Push-Nachrichten können inzwischen unterdrückt werden. 
@ThingsOfficer: Soll die Sichtbarkeit wirklich konfigurierbar sein? Man kann das Boot ja auch verlassen, wenn man es nicht mehr sehen will. Und bei sehr vielen Booten sind die einzelnen Boote eh erstmal "zugeklappt"

**Comment by ThingsOfficer** [comment]
Ne, das passt so wie es ist.

**Comment by reinehr** [comment]
@ThingsOfficer Dann schließe ich das Issue
