### ISSUE TITLE
Dialog, wenn User E-Mail unbekannt

### ISSUE THREAD

**Issue by ThingsOfficer** [reinehr/BoatOfficerMobile#93]
Beim versuchten einloggen mit einer falschen E-Mail kommt keine Antwort.

**Comment by reinehr** [comment]
Außerdem auch bei "Passwort zurücksetzen". Hier gibt es nämlich auch keine Rückmeldung, wenn die E-Mail-Adresse, die man angegeben hat, noch gar nicht registriert ist.
